# Numpy array vs python lists


In [2]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 200000000)]

c = []
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)

1.498225212097168


In [3]:
# numpy
import numpy as np
a= np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time() - start)

0.11317849159240723


In [4]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [6]:
a = np.arange(10000000)

sys.getsizeof(a)

40000112

In [7]:
a = np.arange(10000000, dtype=np.int8)

sys.getsizeof(a)

10000112

# Advanced Indexing

In [15]:
# Normal Indexing and  slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a[1,2]

5

In [11]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [12]:
# fancy Indexing

a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
a[[0,2,3]] # this is call fancy Indexing

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [18]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [20]:
# Boolean Indexing

a = np.random.randint(1,100,24).reshape(6,4)

a

array([[76, 35, 14, 33],
       [74, 44,  1, 91],
       [96, 78, 52, 76],
       [ 2, 75, 23, 84],
       [30, 55, 53, 78],
       [73, 51, 57, 58]])

In [22]:
# find all numbers greater then 50
a>50

array([[ True, False, False, False],
       [ True, False, False,  True],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[a > 50]

array([76, 74, 91, 96, 78, 52, 76, 75, 84, 55, 53, 78, 73, 51, 57, 58])

In [24]:
# find out even numbers
a % 2 == 0

array([[ True, False,  True, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False, False,  True],
       [ True, False, False,  True],
       [False, False, False,  True]])

In [25]:
a[a % 2 == 0]

array([76, 14, 74, 44, 96, 78, 52, 76,  2, 84, 30, 78, 58])

In [26]:
# find all number greater then 50 and are even

a[(a>50) & (a%2 ==0)]

array([76, 74, 96, 78, 52, 76, 84, 78, 58])

In [27]:
# find the numbers not divisible by 7
a[~(a % 7 == 0 )]

array([76, 33, 74, 44,  1, 96, 78, 52, 76,  2, 75, 23, 30, 55, 53, 78, 73,
       51, 57, 58])

# Broadcasting 
 * the term broadcasting describes how Numpy treats arrays with different shapes during arithmetic operation

 * the smaller array  is "broadcast" across the larger array so that they have compatible  shapes.

In [28]:
# same shape 
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [ ]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


# Broadcasting Rules
* 1. Make the two  array have the same number of dimensions
   * If the numbers of dimensions of the two arrays are different , add new dimensions with  size 1 to the head of the array  with the smaller dimension

* 2. make each dimension of the two arrays the same size

  * * If the size of eah dimension of the two  arrays do not match , dimenions with  size 1 are stretched to the size of the other array.
  * * If there is adimension whose size is not 1 in either of two arrays , it cannot be broascasted , and an error is raised.